// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto
// Protobuf Java Version: 4.26.1

package com.grpc.server;

public final class CalculatorProto {
  private CalculatorProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      CalculatorProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.server.AddRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 num1 = 1;</code>
     * @return The num1.
     */
    int getNum1();

    /**
     * <code>int32 num2 = 2;</code>
     * @return The num2.
     */
    int getNum2();
  }
  /**
   * Protobuf type {@code com.grpc.server.AddRequest}
   */
  public static final class AddRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.grpc.server.AddRequest)
      AddRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        AddRequest.class.getName());
    }
    // Use AddRequest.newBuilder() to construct.
    private AddRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AddRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.server.CalculatorProto.AddRequest.class, com.grpc.server.CalculatorProto.AddRequest.Builder.class);
    }

    public static final int NUM1_FIELD_NUMBER = 1;
    private int num1_ = 0;
    /**
     * <code>int32 num1 = 1;</code>
     * @return The num1.
     */
    @java.lang.Override
    public int getNum1() {
      return num1_;
    }

    public static final int NUM2_FIELD_NUMBER = 2;
    private int num2_ = 0;
    /**
     * <code>int32 num2 = 2;</code>
     * @return The num2.
     */
    @java.lang.Override
    public int getNum2() {
      return num2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (num1_ != 0) {
        output.writeInt32(1, num1_);
      }
      if (num2_ != 0) {
        output.writeInt32(2, num2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (num1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num1_);
      }
      if (num2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.server.CalculatorProto.AddRequest)) {
        return super.equals(obj);
      }
      com.grpc.server.CalculatorProto.AddRequest other = (com.grpc.server.CalculatorProto.AddRequest) obj;

      if (getNum1()
          != other.getNum1()) return false;
      if (getNum2()
          != other.getNum2()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUM1_FIELD_NUMBER;
      hash = (53 * hash) + getNum1();
      hash = (37 * hash) + NUM2_FIELD_NUMBER;
      hash = (53 * hash) + getNum2();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpc.server.CalculatorProto.AddRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpc.server.CalculatorProto.AddRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.AddRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.server.CalculatorProto.AddRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.server.AddRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.server.AddRequest)
        com.grpc.server.CalculatorProto.AddRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.server.CalculatorProto.AddRequest.class, com.grpc.server.CalculatorProto.AddRequest.Builder.class);
      }

      // Construct using com.grpc.server.CalculatorProto.AddRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        num1_ = 0;
        num2_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddRequest_descriptor;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.AddRequest getDefaultInstanceForType() {
        return com.grpc.server.CalculatorProto.AddRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.AddRequest build() {
        com.grpc.server.CalculatorProto.AddRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.AddRequest buildPartial() {
        com.grpc.server.CalculatorProto.AddRequest result = new com.grpc.server.CalculatorProto.AddRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpc.server.CalculatorProto.AddRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.num1_ = num1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.num2_ = num2_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.server.CalculatorProto.AddRequest) {
          return mergeFrom((com.grpc.server.CalculatorProto.AddRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.server.CalculatorProto.AddRequest other) {
        if (other == com.grpc.server.CalculatorProto.AddRequest.getDefaultInstance()) return this;
        if (other.getNum1() != 0) {
          setNum1(other.getNum1());
        }
        if (other.getNum2() != 0) {
          setNum2(other.getNum2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                num1_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                num2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int num1_ ;
      /**
       * <code>int32 num1 = 1;</code>
       * @return The num1.
       */
      @java.lang.Override
      public int getNum1() {
        return num1_;
      }
      /**
       * <code>int32 num1 = 1;</code>
       * @param value The num1 to set.
       * @return This builder for chaining.
       */
      public Builder setNum1(int value) {

        num1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num1_ = 0;
        onChanged();
        return this;
      }

      private int num2_ ;
      /**
       * <code>int32 num2 = 2;</code>
       * @return The num2.
       */
      @java.lang.Override
      public int getNum2() {
        return num2_;
      }
      /**
       * <code>int32 num2 = 2;</code>
       * @param value The num2 to set.
       * @return This builder for chaining.
       */
      public Builder setNum2(int value) {

        num2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num2_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.grpc.server.AddRequest)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.server.AddRequest)
    private static final com.grpc.server.CalculatorProto.AddRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.server.CalculatorProto.AddRequest();
    }

    public static com.grpc.server.CalculatorProto.AddRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddRequest>() {
      @java.lang.Override
      public AddRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.server.CalculatorProto.AddRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.server.AddResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    int getResult();
  }
  /**
   * Protobuf type {@code com.grpc.server.AddResponse}
   */
  public static final class AddResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.grpc.server.AddResponse)
      AddResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        AddResponse.class.getName());
    }
    // Use AddResponse.newBuilder() to construct.
    private AddResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AddResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.server.CalculatorProto.AddResponse.class, com.grpc.server.CalculatorProto.AddResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_ = 0;
    /**
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.server.CalculatorProto.AddResponse)) {
        return super.equals(obj);
      }
      com.grpc.server.CalculatorProto.AddResponse other = (com.grpc.server.CalculatorProto.AddResponse) obj;

      if (getResult()
          != other.getResult()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpc.server.CalculatorProto.AddResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpc.server.CalculatorProto.AddResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.AddResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.server.CalculatorProto.AddResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.server.AddResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.server.AddResponse)
        com.grpc.server.CalculatorProto.AddResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.server.CalculatorProto.AddResponse.class, com.grpc.server.CalculatorProto.AddResponse.Builder.class);
      }

      // Construct using com.grpc.server.CalculatorProto.AddResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_AddResponse_descriptor;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.AddResponse getDefaultInstanceForType() {
        return com.grpc.server.CalculatorProto.AddResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.AddResponse build() {
        com.grpc.server.CalculatorProto.AddResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.AddResponse buildPartial() {
        com.grpc.server.CalculatorProto.AddResponse result = new com.grpc.server.CalculatorProto.AddResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpc.server.CalculatorProto.AddResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.server.CalculatorProto.AddResponse) {
          return mergeFrom((com.grpc.server.CalculatorProto.AddResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.server.CalculatorProto.AddResponse other) {
        if (other == com.grpc.server.CalculatorProto.AddResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                result_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>int32 result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(int value) {

        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.grpc.server.AddResponse)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.server.AddResponse)
    private static final com.grpc.server.CalculatorProto.AddResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.server.CalculatorProto.AddResponse();
    }

    public static com.grpc.server.CalculatorProto.AddResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddResponse>
        PARSER = new com.google.protobuf.AbstractParser<AddResponse>() {
      @java.lang.Override
      public AddResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.server.CalculatorProto.AddResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubtractRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.server.SubtractRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 num1 = 1;</code>
     * @return The num1.
     */
    int getNum1();

    /**
     * <code>int32 num2 = 2;</code>
     * @return The num2.
     */
    int getNum2();
  }
  /**
   * Protobuf type {@code com.grpc.server.SubtractRequest}
   */
  public static final class SubtractRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.grpc.server.SubtractRequest)
      SubtractRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SubtractRequest.class.getName());
    }
    // Use SubtractRequest.newBuilder() to construct.
    private SubtractRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SubtractRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.server.CalculatorProto.SubtractRequest.class, com.grpc.server.CalculatorProto.SubtractRequest.Builder.class);
    }

    public static final int NUM1_FIELD_NUMBER = 1;
    private int num1_ = 0;
    /**
     * <code>int32 num1 = 1;</code>
     * @return The num1.
     */
    @java.lang.Override
    public int getNum1() {
      return num1_;
    }

    public static final int NUM2_FIELD_NUMBER = 2;
    private int num2_ = 0;
    /**
     * <code>int32 num2 = 2;</code>
     * @return The num2.
     */
    @java.lang.Override
    public int getNum2() {
      return num2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (num1_ != 0) {
        output.writeInt32(1, num1_);
      }
      if (num2_ != 0) {
        output.writeInt32(2, num2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (num1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num1_);
      }
      if (num2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.server.CalculatorProto.SubtractRequest)) {
        return super.equals(obj);
      }
      com.grpc.server.CalculatorProto.SubtractRequest other = (com.grpc.server.CalculatorProto.SubtractRequest) obj;

      if (getNum1()
          != other.getNum1()) return false;
      if (getNum2()
          != other.getNum2()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUM1_FIELD_NUMBER;
      hash = (53 * hash) + getNum1();
      hash = (37 * hash) + NUM2_FIELD_NUMBER;
      hash = (53 * hash) + getNum2();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpc.server.CalculatorProto.SubtractRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpc.server.CalculatorProto.SubtractRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.SubtractRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.server.CalculatorProto.SubtractRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.server.SubtractRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.server.SubtractRequest)
        com.grpc.server.CalculatorProto.SubtractRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.server.CalculatorProto.SubtractRequest.class, com.grpc.server.CalculatorProto.SubtractRequest.Builder.class);
      }

      // Construct using com.grpc.server.CalculatorProto.SubtractRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        num1_ = 0;
        num2_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractRequest_descriptor;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.SubtractRequest getDefaultInstanceForType() {
        return com.grpc.server.CalculatorProto.SubtractRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.SubtractRequest build() {
        com.grpc.server.CalculatorProto.SubtractRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.SubtractRequest buildPartial() {
        com.grpc.server.CalculatorProto.SubtractRequest result = new com.grpc.server.CalculatorProto.SubtractRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpc.server.CalculatorProto.SubtractRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.num1_ = num1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.num2_ = num2_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.server.CalculatorProto.SubtractRequest) {
          return mergeFrom((com.grpc.server.CalculatorProto.SubtractRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.server.CalculatorProto.SubtractRequest other) {
        if (other == com.grpc.server.CalculatorProto.SubtractRequest.getDefaultInstance()) return this;
        if (other.getNum1() != 0) {
          setNum1(other.getNum1());
        }
        if (other.getNum2() != 0) {
          setNum2(other.getNum2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                num1_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                num2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int num1_ ;
      /**
       * <code>int32 num1 = 1;</code>
       * @return The num1.
       */
      @java.lang.Override
      public int getNum1() {
        return num1_;
      }
      /**
       * <code>int32 num1 = 1;</code>
       * @param value The num1 to set.
       * @return This builder for chaining.
       */
      public Builder setNum1(int value) {

        num1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num1_ = 0;
        onChanged();
        return this;
      }

      private int num2_ ;
      /**
       * <code>int32 num2 = 2;</code>
       * @return The num2.
       */
      @java.lang.Override
      public int getNum2() {
        return num2_;
      }
      /**
       * <code>int32 num2 = 2;</code>
       * @param value The num2 to set.
       * @return This builder for chaining.
       */
      public Builder setNum2(int value) {

        num2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num2_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.grpc.server.SubtractRequest)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.server.SubtractRequest)
    private static final com.grpc.server.CalculatorProto.SubtractRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.server.CalculatorProto.SubtractRequest();
    }

    public static com.grpc.server.CalculatorProto.SubtractRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubtractRequest>
        PARSER = new com.google.protobuf.AbstractParser<SubtractRequest>() {
      @java.lang.Override
      public SubtractRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubtractRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubtractRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.server.CalculatorProto.SubtractRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubtractResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.server.SubtractResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    int getResult();
  }
  /**
   * Protobuf type {@code com.grpc.server.SubtractResponse}
   */
  public static final class SubtractResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.grpc.server.SubtractResponse)
      SubtractResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        SubtractResponse.class.getName());
    }
    // Use SubtractResponse.newBuilder() to construct.
    private SubtractResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SubtractResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.server.CalculatorProto.SubtractResponse.class, com.grpc.server.CalculatorProto.SubtractResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_ = 0;
    /**
     * <code>int32 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.server.CalculatorProto.SubtractResponse)) {
        return super.equals(obj);
      }
      com.grpc.server.CalculatorProto.SubtractResponse other = (com.grpc.server.CalculatorProto.SubtractResponse) obj;

      if (getResult()
          != other.getResult()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpc.server.CalculatorProto.SubtractResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpc.server.CalculatorProto.SubtractResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.server.CalculatorProto.SubtractResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.server.CalculatorProto.SubtractResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.server.SubtractResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.server.SubtractResponse)
        com.grpc.server.CalculatorProto.SubtractResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.server.CalculatorProto.SubtractResponse.class, com.grpc.server.CalculatorProto.SubtractResponse.Builder.class);
      }

      // Construct using com.grpc.server.CalculatorProto.SubtractResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.server.CalculatorProto.internal_static_com_grpc_server_SubtractResponse_descriptor;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.SubtractResponse getDefaultInstanceForType() {
        return com.grpc.server.CalculatorProto.SubtractResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.SubtractResponse build() {
        com.grpc.server.CalculatorProto.SubtractResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.server.CalculatorProto.SubtractResponse buildPartial() {
        com.grpc.server.CalculatorProto.SubtractResponse result = new com.grpc.server.CalculatorProto.SubtractResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpc.server.CalculatorProto.SubtractResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.server.CalculatorProto.SubtractResponse) {
          return mergeFrom((com.grpc.server.CalculatorProto.SubtractResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.server.CalculatorProto.SubtractResponse other) {
        if (other == com.grpc.server.CalculatorProto.SubtractResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                result_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>int32 result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(int value) {

        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.grpc.server.SubtractResponse)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.server.SubtractResponse)
    private static final com.grpc.server.CalculatorProto.SubtractResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.server.CalculatorProto.SubtractResponse();
    }

    public static com.grpc.server.CalculatorProto.SubtractResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubtractResponse>
        PARSER = new com.google.protobuf.AbstractParser<SubtractResponse>() {
      @java.lang.Override
      public SubtractResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubtractResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubtractResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.server.CalculatorProto.SubtractResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_AddRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpc_server_AddRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_AddResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpc_server_AddResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_SubtractRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpc_server_SubtractRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_SubtractResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpc_server_SubtractResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\022\017com.grpc.server\"(\n\nA" +
      "ddRequest\022\014\n\004num1\030\001 \001(\005\022\014\n\004num2\030\002 \001(\005\"\035\n" +
      "\013AddResponse\022\016\n\006result\030\001 \001(\005\"-\n\017Subtract" +
      "Request\022\014\n\004num1\030\001 \001(\005\022\014\n\004num2\030\002 \001(\005\"\"\n\020S" +
      "ubtractResponse\022\016\n\006result\030\001 \001(\0052\237\001\n\nCalc" +
      "ulator\022@\n\003Add\022\033.com.grpc.server.AddReque" +
      "st\032\034.com.grpc.server.AddResponse\022O\n\010Subt" +
      "ract\022 .com.grpc.server.SubtractRequest\032!" +
      ".com.grpc.server.SubtractResponseB-\n\017com" +
      ".grpc.serverB\017CalculatorProtoZ\t./;client" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpc_server_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_server_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpc_server_AddRequest_descriptor,
        new java.lang.String[] { "Num1", "Num2", });
    internal_static_com_grpc_server_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_server_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpc_server_AddResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_grpc_server_SubtractRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_server_SubtractRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpc_server_SubtractRequest_descriptor,
        new java.lang.String[] { "Num1", "Num2", });
    internal_static_com_grpc_server_SubtractResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpc_server_SubtractResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpc_server_SubtractResponse_descriptor,
        new java.lang.String[] { "Result", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
