version: "3.7"

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    ports:
      - "50070:50070" # HDFS 웹 UI
      - "8020:8020" # NameNode 통신
    volumes:
      - namenode_data:/data # NameNode 데이터 저장
    environment:
      - CLUSTER_NAME=mycluster

  datanode1:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode1
    depends_on:
      - namenode
    ports:
      - "50075:50075" # DataNode 웹 UI
      - "8021:8021" # DataNode 통신
    volumes:
      - datanode1_data:/data # DataNode 데이터 저장
    environment:
      - CLUSTER_NAME=mycluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  datanode2:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode2
    depends_on:
      - namenode
    ports:
      - "50080:50080" # DataNode 웹 UI
      - "8022:8022" # DataNode 통신
    volumes:
      - datanode2_data:/data # DataNode 데이터 저장
    environment:
      - CLUSTER_NAME=mycluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
